### ISSUE TITLE
Error: Functions cannot contain functions

### ISSUE THREAD

**Issue by codychen98** [Tebayaki/HotGestures#1]
I'm running Autohotkey Version 1.1.36.02, and I get the following error. Just wondering if you have the same issue, thank!

![Autohotkey_Li67Ibvmlj](https://github.com/Tebayaki/HotGestures/assets/107047989/7216a496-ff36-4ddf-af09-6c405078f58d)

**Comment by Tebayaki** [comment]
This library requires v2.
